id: 7b0296a722bd46239f65b8c1dd4a9b53
initial_creation_type: ocr
source_metadata:
  volumes:
    3ba71488795a458295b5b8ef10d8758b:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཐེག་པ་ཆེན་པོ་ཉི་ཤུ་པ།
      total_pages: 1605
      volume_number: 57
