id: 7b0296a722bd46239f65b8c1dd4a9b53
initial_creation_type: ocr
source_metadata:
  volumes:
    8708055789d042ad93afbfe37bf8a926:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
