id: DEFF4BFA6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:34:28+00:00'
last_modified: '2022-05-27T05:47:17.961390+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4f59:
      image_group_id: I1PD95902
      title: ཐེག་པ་ཆེན་པོ་ཉི་ཤུ་པ།
      total_pages: 1605
      order: 57
      base_file: 4f59.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
